export type Order = {
  id: string;
  date: string;
  customer: string;
  amount: number;
  status: "paid" | "pending" | "flagged";
};

export const mockOrders: Order[] = [
  { id: "AC-1042", date: "2026-04-03", customer: "Nordlicht GmbH", amount: 1280, status: "paid" },
  { id: "AC-1048", date: "2026-04-08", customer: "Maison Valette", amount: 2485, status: "pending" },
  { id: "AC-1051", date: "2026-04-14", customer: "Oslo Marine AS", amount: 975, status: "paid" },
  { id: "AC-1060", date: "2026-04-22", customer: "Rhein Metalworks", amount: 3310, status: "flagged" },
  { id: "AC-1068", date: "2026-04-29", customer: "Turing Textiles", amount: 760, status: "pending" },
  { id: "AC-1077", date: "2026-05-02", customer: "Iberia Logistics", amount: 1440, status: "paid" },
  { id: "AC-1019", date: "2026-03-18", customer: "Baltic Paper Co", amount: 2120, status: "paid" },
  { id: "AC-0998", date: "2026-02-24", customer: "Acme Components", amount: 420, status: "pending" },
];

export type Invoice = {
  invoiceId: string;
  vendorName: string;
  amount: number;
  dueDate: string;
  status: "overdue" | "pending" | "paid";
  riskFlag: "none" | "review" | "blocked";
  description: string;
  paymentTerms: string;
  bankAccountLast4: string;
  bankCountry: string;
};

export const mockInvoices: Invoice[] = [
  {
    invoiceId: "INV-24017",
    vendorName: "Nordlicht Components GmbH",
    amount: 12800,
    dueDate: "2026-04-12",
    status: "overdue",
    riskFlag: "review",
    description: "Quarterly control-board shipment for EU West warehouse",
    paymentTerms: "Net 30",
    bankAccountLast4: "8842",
    bankCountry: "DE",
  },
  {
    invoiceId: "INV-24031",
    vendorName: "Maison Valette Packaging",
    amount: 7600,
    dueDate: "2026-04-21",
    status: "overdue",
    riskFlag: "none",
    description: "Custom packaging materials for retail batch 19",
    paymentTerms: "Net 15",
    bankAccountLast4: "2190",
    bankCountry: "FR",
  },
  {
    invoiceId: "INV-24038",
    vendorName: "Oslo Marine Logistics",
    amount: 15450,
    dueDate: "2026-04-25",
    status: "overdue",
    riskFlag: "blocked",
    description: "Expedited freight charges for Nordic ports",
    paymentTerms: "Due on receipt",
    bankAccountLast4: "4417",
    bankCountry: "NO",
  },
  {
    invoiceId: "INV-24044",
    vendorName: "Rhein Metalworks",
    amount: 6950,
    dueDate: "2026-04-28",
    status: "overdue",
    riskFlag: "none",
    description: "Replacement conveyor brackets and installation hardware",
    paymentTerms: "Net 30",
    bankAccountLast4: "6621",
    bankCountry: "DE",
  },
  {
    invoiceId: "INV-24051",
    vendorName: "Turing Textiles",
    amount: 4200,
    dueDate: "2026-04-29",
    status: "overdue",
    riskFlag: "none",
    description: "Uniform fabric replenishment",
    paymentTerms: "Net 45",
    bankAccountLast4: "1092",
    bankCountry: "GB",
  },
  {
    invoiceId: "INV-24062",
    vendorName: "Iberia Facility Services",
    amount: 8700,
    dueDate: "2026-05-18",
    status: "pending",
    riskFlag: "review",
    description: "Preventive maintenance for Madrid facility",
    paymentTerms: "Net 30",
    bankAccountLast4: "7304",
    bankCountry: "ES",
  },
  {
    invoiceId: "INV-24069",
    vendorName: "Baltic Paper Co",
    amount: 22400,
    dueDate: "2026-03-31",
    status: "overdue",
    riskFlag: "review",
    description: "Annual paper-stock replenishment for invoice archive program",
    paymentTerms: "Net 60",
    bankAccountLast4: "5528",
    bankCountry: "SE",
  },
  {
    invoiceId: "INV-24074",
    vendorName: "Lombardi Tooling SRL",
    amount: 9800,
    dueDate: "2026-04-07",
    status: "overdue",
    riskFlag: "none",
    description: "Precision tooling inserts for Milan production cell",
    paymentTerms: "Net 30",
    bankAccountLast4: "3410",
    bankCountry: "IT",
  },
  {
    invoiceId: "INV-24079",
    vendorName: "North Sea Freight BV",
    amount: 31500,
    dueDate: "2026-04-10",
    status: "overdue",
    riskFlag: "blocked",
    description: "Container demurrage and customs handling charges",
    paymentTerms: "Due on receipt",
    bankAccountLast4: "9027",
    bankCountry: "NL",
  },
  {
    invoiceId: "INV-24083",
    vendorName: "Glasgow Safety Systems",
    amount: 5300,
    dueDate: "2026-04-19",
    status: "overdue",
    riskFlag: "none",
    description: "Warehouse safety sensor inspection and replacement parts",
    paymentTerms: "Net 15",
    bankAccountLast4: "7781",
    bankCountry: "GB",
  },
  {
    invoiceId: "INV-24091",
    vendorName: "Lisbon Facility Services",
    amount: 11800,
    dueDate: "2026-05-09",
    status: "pending",
    riskFlag: "none",
    description: "Preventive maintenance for Lisbon distribution center",
    paymentTerms: "Net 30",
    bankAccountLast4: "4509",
    bankCountry: "PT",
  },
  {
    invoiceId: "INV-24097",
    vendorName: "Acme Components US",
    amount: 26600,
    dueDate: "2026-05-14",
    status: "pending",
    riskFlag: "blocked",
    description: "High-value replacement controller shipment",
    paymentTerms: "Net 45",
    bankAccountLast4: "0874",
    bankCountry: "US",
  },
  {
    invoiceId: "INV-24103",
    vendorName: "Stockholm Grid Analytics",
    amount: 6400,
    dueDate: "2026-05-20",
    status: "pending",
    riskFlag: "none",
    description: "Demand forecast analytics subscription",
    paymentTerms: "Net 30",
    bankAccountLast4: "6342",
    bankCountry: "SE",
  },
  {
    invoiceId: "INV-24109",
    vendorName: "Prague Assembly Works",
    amount: 14300,
    dueDate: "2026-04-02",
    status: "paid",
    riskFlag: "none",
    description: "Final assembly fixtures paid under April batch close",
    paymentTerms: "Net 30",
    bankAccountLast4: "1189",
    bankCountry: "CZ",
  },
  {
    invoiceId: "INV-24112",
    vendorName: "Dublin Compliance Labs",
    amount: 7200,
    dueDate: "2026-04-06",
    status: "paid",
    riskFlag: "review",
    description: "Regulatory certification audit paid after manual review",
    paymentTerms: "Net 15",
    bankAccountLast4: "3915",
    bankCountry: "IE",
  },
  {
    invoiceId: "INV-24118",
    vendorName: "Valencia Cold Chain",
    amount: 4800,
    dueDate: "2026-04-23",
    status: "paid",
    riskFlag: "none",
    description: "Temperature-controlled freight lane settlement",
    paymentTerms: "Net 30",
    bankAccountLast4: "2604",
    bankCountry: "ES",
  },
  {
    invoiceId: "INV-24125",
    vendorName: "Warsaw Robotics Spares",
    amount: 18750,
    dueDate: "2026-03-28",
    status: "overdue",
    riskFlag: "review",
    description: "Robot arm replacement assemblies for line 4",
    paymentTerms: "Net 45",
    bankAccountLast4: "9913",
    bankCountry: "PL",
  },
  {
    invoiceId: "INV-24131",
    vendorName: "Helsinki Calibration Oy",
    amount: 3800,
    dueDate: "2026-04-17",
    status: "overdue",
    riskFlag: "none",
    description: "Calibration service below payment packet threshold",
    paymentTerms: "Net 30",
    bankAccountLast4: "5066",
    bankCountry: "FI",
  },
  {
    invoiceId: "INV-24136",
    vendorName: "Zurich Insurance Brokers",
    amount: 24200,
    dueDate: "2026-05-28",
    status: "pending",
    riskFlag: "review",
    description: "Annual cargo insurance policy renewal",
    paymentTerms: "Net 30",
    bankAccountLast4: "8144",
    bankCountry: "CH",
  },
  {
    invoiceId: "INV-24142",
    vendorName: "Rotterdam Port Services",
    amount: 9100,
    dueDate: "2026-04-15",
    status: "paid",
    riskFlag: "none",
    description: "Port storage fees paid after shipment release",
    paymentTerms: "Due on receipt",
    bankAccountLast4: "7341",
    bankCountry: "NL",
  },
  {
    invoiceId: "INV-24149",
    vendorName: "Munich Controls AG",
    amount: 56000,
    dueDate: "2026-04-01",
    status: "overdue",
    riskFlag: "blocked",
    description: "Critical control cabinet replacement order",
    paymentTerms: "Due on receipt",
    bankAccountLast4: "0448",
    bankCountry: "DE",
  },
  {
    invoiceId: "INV-24155",
    vendorName: "Marseille Logistics",
    amount: 6100,
    dueDate: "2026-05-24",
    status: "pending",
    riskFlag: "none",
    description: "Southern France final-mile freight lane",
    paymentTerms: "Net 15",
    bankAccountLast4: "6720",
    bankCountry: "FR",
  },
  {
    invoiceId: "INV-24161",
    vendorName: "Copenhagen Energy Systems",
    amount: 12400,
    dueDate: "2026-04-11",
    status: "paid",
    riskFlag: "blocked",
    description: "Energy backup system paid after executive override",
    paymentTerms: "Net 30",
    bankAccountLast4: "3057",
    bankCountry: "DK",
  },
];
